In [1]:
import pandas as pd
import numpy as np
import re


In [2]:
df = pd.read_csv(r'C:/Users/OMKAR/Desktop/Practice/Food_Data_Processing/Data/food_coded_uncleaned.csv')

In [3]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

In [4]:
df.tail()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
120    3.5       1          1               610           4.0           420.0   
121      3       1          1               265           2.0           315.0   
122  3.882       1          1               720           NaN           420.0   
123      3       2          1               720           4.0           420.0   
124    3.9       1          1               430           NaN           315.0   

     coffee                             comfort_food  \
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3         1   
124             725.0              345          NaN           4         2   

     waffle_calories  weight  
120             1315     156  
121             1315     180  
122             1315     120  
123             1315     135  
124              575     135  

[5 rows x 61 columns]

In [5]:
df.shape

(125, 61)

In [6]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         21
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [7]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       

#### GPA

In [8]:
df['GPA']

0        2.4
1      3.654
2        3.3
3        3.2
4        3.5
       ...  
120      3.5
121        3
122    3.882
123        3
124      3.9
Name: GPA, Length: 125, dtype: object

In [9]:
df['GPA'].isnull().sum()

2

In [10]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '3.79 bitch', '2.71', '3.68',
       '3.75', '3.92', 'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [11]:
df['GPA'] = df['GPA'].replace('[a-z[A-Z]', '', regex = True)
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', ' ',
       '2.6', '3.67', '3.73', '3.79 ', '2.71', '3.68', '3.75', '3.92', '',
       '3.77', '3.63', '3.882'], dtype=object)

In [36]:
df['GPA'] = df['GPA'].replace('', np.nan)
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', '2.6',
       '3.67', '3.73', '3.79 ', '2.71', '3.68', '3.75', '3.92', '3.77',
       '3.63', '3.882'], dtype=object)

In [37]:
df['GPA'] = df['GPA'].apply(lambda x: '{:.1f}'.format(round(float(x), 1)))
df['GPA']

0      2.4
1      3.7
2      3.3
3      3.2
4      3.5
      ... 
120    3.5
121    3.0
122    3.9
123    3.0
124    3.9
Name: GPA, Length: 125, dtype: object

In [14]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

#### Gender

In [15]:
df['Gender'].isnull().sum()

0

In [16]:
df['Gender'].unique()

array([2, 1], dtype=int64)

In [17]:
df['Gender'] = df['Gender'].replace({1 :  'Female', 2 : 'Male'})

In [18]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4    Male          1               430           NaN           315.0   
1  3.654  Female          1               610           3.0           420.0   
2    3.3  Female          1               720           4.0           420.0   
3    3.2  Female          1               430           3.0           420.0   
4    3.5  Female          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

####  Breakfast

In [19]:
df['breakfast'].isnull().sum()

0

In [20]:
df['breakfast'].unique()

array([1, 2], dtype=int64)

In [21]:
df['breakfast'] = df['breakfast'].replace({1 : 'Cereal', 2 : 'Donut'})
df['breakfast']

0      Cereal
1      Cereal
2      Cereal
3      Cereal
4      Cereal
        ...  
120    Cereal
121    Cereal
122    Cereal
123    Cereal
124    Cereal
Name: breakfast, Length: 125, dtype: object

In [22]:
df['breakfast'].unique()

array(['Cereal', 'Donut'], dtype=object)

In [23]:
df.head()

GPA  Gender breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4    Male    Cereal               430           NaN           315.0   
1  3.654  Female    Cereal               610           3.0           420.0   
2    3.3  Female    Cereal               720           4.0           420.0   
3    3.2  Female    Cereal               430           3.0           420.0   
4    3.5  Female    Cereal               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

#### Calories_chicken


In [24]:
df['calories_chicken'].isnull().sum()

0

In [25]:
df['calories_chicken'].unique()

array([430, 610, 720, 265], dtype=int64)

In [26]:
df['calories_chicken'] = df['calories_chicken'].replace({265 : 1, 430 : 2, 610 : 3, 720 : 4})
df['calories_chicken']

0      2
1      3
2      4
3      2
4      4
      ..
120    3
121    1
122    4
123    4
124    2
Name: calories_chicken, Length: 125, dtype: int64

In [27]:
df

GPA  Gender breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4    Male    Cereal                 2           NaN           315.0   
1    3.654  Female    Cereal                 3           3.0           420.0   
2      3.3  Female    Cereal                 4           4.0           420.0   
3      3.2  Female    Cereal                 2           3.0           420.0   
4      3.5  Female    Cereal                 4           2.0           420.0   
..     ...     ...       ...               ...           ...             ...   
120    3.5  Female    Cereal                 3           4.0           420.0   
121      3  Female    Cereal                 1           2.0           315.0   
122  3.882  Female    Cereal                 4           NaN           420.0   
123      3    Male    Cereal                 4           4.0           420.0   
124    3.9  Female    Cereal                 2           NaN           315.0   

     coffee                             comfort_food  \
0         1                                     none   
1         2              chocolate, chips, ice cream   
2         2          frozen yogurt, pizza, fast food   
3         2         Pizza, Mac and cheese, ice cream   
4         2             Ice cream, chocolate, chips    
..      ...                                      ...   
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1   
1                           1.0  ...   1.0     1.0          2   
2                           1.0  ...   1.0     2.0          5   
3                           2.0  ...   1.0     2.0          5   
4                           1.0  ...   1.0     1.0          4   
..                          ...  ...   ...     ...        ...   
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1   
1               725.0              690  Basketball            4         2   
2              1165.0              500         none           5         1   
3               725.0              690          NaN           3         1   
4               940.0              500     Softball           4         2   
..                ...              ...          ...         ...       ...   
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3         1   
124             725.0              345          NaN           4         2   

     waffle_calori

#### calories day

In [28]:
df['calories_day'].isnull().sum()

19

In [29]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [30]:
df['calories_day'] = df['calories_day'].astype(str).str.replace('\.0$', '')

C:\Users\OMKAR\AppData\Local\Temp/ipykernel_6380/1536826737.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['calories_day'] = df['calories_day'].astype(str).str.replace('\.0$', '')


In [31]:
df['calories_day'].unique()

array(['nan', '3', '4', '2'], dtype=object)

In [32]:
df['calories_day'] = df['calories_day'].replace({
    '1' : "Don't know how many calorie should consume",
    '2' : "Not at all important",
    '3' : "Moderatelly important",
    '4' : "Very Important"
})

In [33]:
df['calories_day']

0                        nan
1      Moderatelly important
2             Very Important
3      Moderatelly important
4       Not at all important
               ...          
120           Very Important
121     Not at all important
122                      nan
123           Very Important
124                      nan
Name: calories_day, Length: 125, dtype: object

In [34]:
df

GPA  Gender breakfast  calories_chicken           calories_day  \
0      2.4    Male    Cereal                 2                    nan   
1    3.654  Female    Cereal                 3  Moderatelly important   
2      3.3  Female    Cereal                 4         Very Important   
3      3.2  Female    Cereal                 2  Moderatelly important   
4      3.5  Female    Cereal                 4   Not at all important   
..     ...     ...       ...               ...                    ...   
120    3.5  Female    Cereal                 3         Very Important   
121      3  Female    Cereal                 1   Not at all important   
122  3.882  Female    Cereal                 4                    nan   
123      3    Male    Cereal                 4         Very Important   
124    3.9  Female    Cereal                 2                    nan   

     calories_scone  coffee                             comfort_food  \
0             315.0       1                                     none   
1             420.0       2              chocolate, chips, ice cream   
2             420.0       2          frozen yogurt, pizza, fast food   
3             420.0       2         Pizza, Mac and cheese, ice cream   
4             420.0       2             Ice cream, chocolate, chips    
..              ...     ...                                      ...   
120           420.0       2  wine. mac and cheese, pizza, ice cream    
121           315.0       2               Pizza / Wings / Cheesecake   
122           420.0       1               rice, potato, seaweed soup   
123           420.0       1             Mac n Cheese, Lasagna, Pizza   
124           315.0       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1   
1                           1.0  ...   1.0     1.0          2   
2                           1.0  ...   1.0     2.0          5   
3                           2.0  ...   1.0     2.0          5   
4                           1.0  ...   1.0     1.0          4   
..                          ...  ...   ...     ...        ...   
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1   
1               725.0              690  Basketball            4         2   
2              1165.0              500         none           5         1   
3               725.0              690          NaN           3         1   
4               940.0              500     Softball           4         2   
..                ...              ...          ...         ...       ...   
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3  

#### calories_scone

In [35]:
df['calories_scone'].isnull().sum()

1

In [38]:
df['calories_scone'].unique()

array([315., 420., 980.,  nan])

In [46]:
df['calories_scone'] = df['calories_scone'].df['values'] = df['values'].astype(int)
df['calories_scone'].unique()

array(['3150', '4200', '9800', 'nan'], dtype=object)

In [56]:
df['calories_scone'] = pd.to_numeric(df['calories_scone'], errors='coerce').fillna(0).astype(int) // 10

In [57]:
df['calories_scone']

0      315
1      420
2      420
3      420
4      420
      ... 
120    420
121    315
122    420
123    420
124    315
Name: calories_scone, Length: 125, dtype: int32

In [58]:
df['calories_scone'] = df['calories_scone'].replace({
    107 : "107 cal",
    315 : "315 cal",
    420 : "420 cal",
    980 : "980 cal"
})

In [59]:
df['calories_scone']

0      315 cal
1      420 cal
2      420 cal
3      420 cal
4      420 cal
        ...   
120    420 cal
121    315 cal
122    420 cal
123    420 cal
124    315 cal
Name: calories_scone, Length: 125, dtype: object

In [60]:
df

GPA  Gender breakfast  calories_chicken           calories_day  \
0    2.4    Male    Cereal                 2                    nan   
1    3.7  Female    Cereal                 3  Moderatelly important   
2    3.3  Female    Cereal                 4         Very Important   
3    3.2  Female    Cereal                 2  Moderatelly important   
4    3.5  Female    Cereal                 4   Not at all important   
..   ...     ...       ...               ...                    ...   
120  3.5  Female    Cereal                 3         Very Important   
121  3.0  Female    Cereal                 1   Not at all important   
122  3.9  Female    Cereal                 4                    nan   
123  3.0    Male    Cereal                 4         Very Important   
124  3.9  Female    Cereal                 2                    nan   

    calories_scone  coffee                             comfort_food  \
0          315 cal       1                                     none   
1          420 cal       2              chocolate, chips, ice cream   
2          420 cal       2          frozen yogurt, pizza, fast food   
3          420 cal       2         Pizza, Mac and cheese, ice cream   
4          420 cal       2             Ice cream, chocolate, chips    
..             ...     ...                                      ...   
120        420 cal       2  wine. mac and cheese, pizza, ice cream    
121        315 cal       2               Pizza / Wings / Cheesecake   
122        420 cal       1               rice, potato, seaweed soup   
123        420 cal       1             Mac n Cheese, Lasagna, Pizza   
124        315 cal       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1   
1                           1.0  ...   1.0     1.0          2   
2                           1.0  ...   1.0     2.0          5   
3                           2.0  ...   1.0     2.0          5   
4                           1.0  ...   1.0     1.0          4   
..                          ...  ...   ...     ...        ...   
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1   
1               725.0              690  Basketball            4         2   
2              1165.0              500         none           5         1   
3               725.0              690          NaN           3         1   
4               940.0              500     Softball           4         2   
..                ...              ...          ...         ...       ...   
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3         1   
124             725.0 

#### coffee

In [62]:
df['coffee'].isnull().sum()

0

In [63]:
df['coffee'].unique()

array([1, 2], dtype=int64)

In [66]:
df['coffee'] = df['coffee'].replace({
    1 : "Creamy frapuccino",
    2 : "Expresso"
})
df['coffee'].unique()

array(['Creamy frapuccino', 'Expresso'], dtype=object)

In [67]:
df

GPA  Gender breakfast  calories_chicken           calories_day  \
0    2.4    Male    Cereal                 2                    nan   
1    3.7  Female    Cereal                 3  Moderatelly important   
2    3.3  Female    Cereal                 4         Very Important   
3    3.2  Female    Cereal                 2  Moderatelly important   
4    3.5  Female    Cereal                 4   Not at all important   
..   ...     ...       ...               ...                    ...   
120  3.5  Female    Cereal                 3         Very Important   
121  3.0  Female    Cereal                 1   Not at all important   
122  3.9  Female    Cereal                 4                    nan   
123  3.0    Male    Cereal                 4         Very Important   
124  3.9  Female    Cereal                 2                    nan   

    calories_scone             coffee  \
0          315 cal  Creamy frapuccino   
1          420 cal           Expresso   
2          420 cal           Expresso   
3          420 cal           Expresso   
4          420 cal           Expresso   
..             ...                ...   
120        420 cal           Expresso   
121        315 cal           Expresso   
122        420 cal  Creamy frapuccino   
123        420 cal  Creamy frapuccino   
124        315 cal           Expresso   

                                comfort_food  \
0                                       none   
1                chocolate, chips, ice cream   
2            frozen yogurt, pizza, fast food   
3           Pizza, Mac and cheese, ice cream   
4               Ice cream, chocolate, chips    
..                                       ...   
120  wine. mac and cheese, pizza, ice cream    
121               Pizza / Wings / Cheesecake   
122               rice, potato, seaweed soup   
123             Mac n Cheese, Lasagna, Pizza   
124             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1   
1                           1.0  ...   1.0     1.0          2   
2                           1.0  ...   1.0     2.0          5   
3                           2.0  ...   1.0     2.0          5   
4                           1.0  ...   1.0     1.0          4   
..                          ...  ...   ...     ...        ...   
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1   
1               725.0              690  Basketball            4         2   
2              1165.0              500         none           5         1   
3               725.0              690          NaN           3         1   
4               940.0              500     Softball           4         2   
..                ...              ...          ...         ...       ...   
120             940.0              500     Softball           5         1   
121             940.0              5

#### comfort food

In [68]:
df['comfort_food'].isnull().sum()

1

In [69]:
df['comfort_food'].unique()

array(['none', 'chocolate, chips, ice cream',
       'frozen yogurt, pizza, fast food',
       'Pizza, Mac and cheese, ice cream', 'Ice cream, chocolate, chips ',
       'Candy, brownies and soda.',
       'Chocolate, ice cream, french fries, pretzels',
       'Ice cream, cheeseburgers, chips.', 'Donuts, ice cream, chips',
       'Mac and cheese, chocolate, and pasta ',
       'Pasta, grandma homemade chocolate cake anything homemade ',
       'chocolate, pasta, soup, chips, popcorn',
       'Cookies, popcorn, and chips', 'ice cream, cake, chocolate',
       'Pizza, fruit, spaghetti, chicken and Potatoes  ',
       'cookies, donuts, candy bars', 'Saltfish, Candy and Kit Kat ',
       'chips, cookies, ice cream', 'Chocolate, ice crea ',
       'pizza, wings, Chinese', 'Fast food, pizza, subs',
       'chocolate, sweets, ice cream', 'burgers, chips, cookies',
       'Chilli, soup, pot pie', 'Soup, pasta, brownies, cake',
       'chocolate, ice cream/milkshake, cookies',
       'Chips, ic

In [71]:
df['comfort_food'] = df['comfort_food'].str.replace('\r', '', regex = True)

In [72]:
df['comfort_food'].unique()

array(['none', 'chocolate, chips, ice cream',
       'frozen yogurt, pizza, fast food',
       'Pizza, Mac and cheese, ice cream', 'Ice cream, chocolate, chips ',
       'Candy, brownies and soda.',
       'Chocolate, ice cream, french fries, pretzels',
       'Ice cream, cheeseburgers, chips.', 'Donuts, ice cream, chips',
       'Mac and cheese, chocolate, and pasta ',
       'Pasta, grandma homemade chocolate cake anything homemade ',
       'chocolate, pasta, soup, chips, popcorn',
       'Cookies, popcorn, and chips', 'ice cream, cake, chocolate',
       'Pizza, fruit, spaghetti, chicken and Potatoes  ',
       'cookies, donuts, candy bars', 'Saltfish, Candy and Kit Kat ',
       'chips, cookies, ice cream', 'Chocolate, ice crea ',
       'pizza, wings, Chinese', 'Fast food, pizza, subs',
       'chocolate, sweets, ice cream', 'burgers, chips, cookies',
       'Chilli, soup, pot pie', 'Soup, pasta, brownies, cake',
       'chocolate, ice cream/milkshake, cookies',
       'Chips, ic

#### comfort food reasons

In [73]:
df['comfort_food_reasons'].isnull().sum()

1

In [74]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

#### comfort food reasons coded

In [75]:
df['comfort_food_reasons_coded'].isnull().sum()

19

In [76]:
df['comfort_food_reasons_coded'].unique()

array([ 9.,  1.,  2.,  4.,  3.,  7.,  6.,  5.,  8., nan])

In [80]:
df['comfort_food_reasons_coded'].dtype

dtype('float64')

In [82]:
df['comfort_food_reasons_coded'] = df['comfort_food_reasons_coded'].fillna(0).astype(int)

In [83]:
df['comfort_food_reasons_coded'].unique()

array([9, 1, 2, 4, 3, 7, 6, 5, 8, 0])

In [84]:
df['comfort_food_reasons_coded'] = df['comfort_food_reasons_coded'].replace({
    1 : "Stress",
    2 : "Boredum",
    3 : "Depression/Sadness",
    4 : "Hunger",
    5 : "Laziness",
    6 : "Cold Weather",
    7 : "Happiness",
    8 : "Watching TV",
    9 : "none"
})

In [85]:
df['comfort_food_reasons_coded'].unique()

array(['none', 'Stress', 'Boredum', 'Hunger', 'Depression/Sadness',
       'Happiness', 'Cold Weather', 'Laziness', 'Watching TV', 0],
      dtype=object)

In [87]:
df.head()

GPA  Gender breakfast  calories_chicken           calories_day  \
0  2.4    Male    Cereal                 2                    nan   
1  3.7  Female    Cereal                 3  Moderatelly important   
2  3.3  Female    Cereal                 4         Very Important   
3  3.2  Female    Cereal                 2  Moderatelly important   
4  3.5  Female    Cereal                 4   Not at all important   

  calories_scone             coffee                      comfort_food  \
0        315 cal  Creamy frapuccino                              none   
1        420 cal           Expresso       chocolate, chips, ice cream   
2        420 cal           Expresso   frozen yogurt, pizza, fast food   
3        420 cal           Expresso  Pizza, Mac and cheese, ice cream   
4        420 cal           Expresso      Ice cream, chocolate, chips    

         comfort_food_reasons comfort_food_reasons_coded  ...  soup  sports  \
0       we dont have comfort                        none  ...   1.0     1.0   
1        Stress, bored, anger                     Stress  ...   1.0     1.0   
2             stress, sadness                     Stress  ...   1.0     2.0   
3                     Boredom                    Boredum  ...   1.0     2.0   
4  Stress, boredom, cravings                      Stress  ...   1.0     1.0   

   thai_food tortilla_calories  turkey_calories  type_sports veggies_day  \
0          1            1165.0              345   car racing           5   
1          2             725.0              690  Basketball            4   
2          5            1165.0              500         none           5   
3          5             725.0              690          NaN           3   
4          4             940.0              500     Softball           4   

   vitamins  waffle_calories                    weight  
0         1             1315                       187  
1         2              900                       155  
2         1              900  I'm not answering this.   
3         1             1315             Not sure, 240  
4         2              760                       190  

[5 rows x 61 columns]

In [88]:
df = df.drop(columns = ['comfort_food_reasons'])

In [89]:
df

GPA  Gender breakfast  calories_chicken           calories_day  \
0    2.4    Male    Cereal                 2                    nan   
1    3.7  Female    Cereal                 3  Moderatelly important   
2    3.3  Female    Cereal                 4         Very Important   
3    3.2  Female    Cereal                 2  Moderatelly important   
4    3.5  Female    Cereal                 4   Not at all important   
..   ...     ...       ...               ...                    ...   
120  3.5  Female    Cereal                 3         Very Important   
121  3.0  Female    Cereal                 1   Not at all important   
122  3.9  Female    Cereal                 4                    nan   
123  3.0    Male    Cereal                 4         Very Important   
124  3.9  Female    Cereal                 2                    nan   

    calories_scone             coffee  \
0          315 cal  Creamy frapuccino   
1          420 cal           Expresso   
2          420 cal           Expresso   
3          420 cal           Expresso   
4          420 cal           Expresso   
..             ...                ...   
120        420 cal           Expresso   
121        315 cal           Expresso   
122        420 cal  Creamy frapuccino   
123        420 cal  Creamy frapuccino   
124        315 cal           Expresso   

                                comfort_food comfort_food_reasons_coded  cook  \
0                                       none                       none   2.0   
1                chocolate, chips, ice cream                     Stress   3.0   
2            frozen yogurt, pizza, fast food                     Stress   1.0   
3           Pizza, Mac and cheese, ice cream                    Boredum   2.0   
4               Ice cream, chocolate, chips                      Stress   1.0   
..                                       ...                        ...   ...   
120  wine. mac and cheese, pizza, ice cream                           0   3.0   
121               Pizza / Wings / Cheesecake                          0   3.0   
122               rice, potato, seaweed soup                          0   3.0   
123             Mac n Cheese, Lasagna, Pizza                          0   3.0   
124             Chocolates, pizza, and Ritz.                          0   NaN   

     ...  soup  sports thai_food  tortilla_calories  turkey_calories  \
0    ...   1.0     1.0         1             1165.0              345   
1    ...   1.0     1.0         2              725.0              690   
2    ...   1.0     2.0         5             1165.0              500   
3    ...   1.0     2.0         5              725.0              690   
4    ...   1.0     1.0         4              940.0              500   
..   ...   ...     ...       ...                ...              ...   
120  ...   1.0     1.0         5              940.0              500   
121  ...   1.0     NaN         4              940.0              500   
122  ...   1.0     2.0         5              580.0              690   
123  ...   2.0     2.0         1              940.0              500   
124  ...   1.0     2.0         2              725.0              345   

     type_sports  veggies_day  vitamins  waffle_calories  \
0     car racing            5         1             1315   
1    Basketball             4         2              900   
2           none            5         1              900   
3            NaN            3         1             1315   
4       Softball            4         2              760   
..           ...          ...       ...              ...   
120     Softball            5         1             1315   
121  basketball             5         2             1315   
122         none            4         2             1315   
123          NaN            3         1             1315   
124          NaN            4         2              575   

                       weight  
0                         187  
1                         155  
2   

In [90]:
df = df.rename(columns = {'comfort_food_reasons_coded' : 'comfort_food_reasons'})

In [91]:
df

GPA  Gender breakfast  calories_chicken           calories_day  \
0    2.4    Male    Cereal                 2                    nan   
1    3.7  Female    Cereal                 3  Moderatelly important   
2    3.3  Female    Cereal                 4         Very Important   
3    3.2  Female    Cereal                 2  Moderatelly important   
4    3.5  Female    Cereal                 4   Not at all important   
..   ...     ...       ...               ...                    ...   
120  3.5  Female    Cereal                 3         Very Important   
121  3.0  Female    Cereal                 1   Not at all important   
122  3.9  Female    Cereal                 4                    nan   
123  3.0    Male    Cereal                 4         Very Important   
124  3.9  Female    Cereal                 2                    nan   

    calories_scone             coffee  \
0          315 cal  Creamy frapuccino   
1          420 cal           Expresso   
2          420 cal           Expresso   
3          420 cal           Expresso   
4          420 cal           Expresso   
..             ...                ...   
120        420 cal           Expresso   
121        315 cal           Expresso   
122        420 cal  Creamy frapuccino   
123        420 cal  Creamy frapuccino   
124        315 cal           Expresso   

                                comfort_food comfort_food_reasons  cook  ...  \
0                                       none                 none   2.0  ...   
1                chocolate, chips, ice cream               Stress   3.0  ...   
2            frozen yogurt, pizza, fast food               Stress   1.0  ...   
3           Pizza, Mac and cheese, ice cream              Boredum   2.0  ...   
4               Ice cream, chocolate, chips                Stress   1.0  ...   
..                                       ...                  ...   ...  ...   
120  wine. mac and cheese, pizza, ice cream                     0   3.0  ...   
121               Pizza / Wings / Cheesecake                    0   3.0  ...   
122               rice, potato, seaweed soup                    0   3.0  ...   
123             Mac n Cheese, Lasagna, Pizza                    0   3.0  ...   
124             Chocolates, pizza, and Ritz.                    0   NaN  ...   

     soup  sports thai_food  tortilla_calories  turkey_calories  type_sports  \
0     1.0     1.0         1             1165.0              345   car racing   
1     1.0     1.0         2              725.0              690  Basketball    
2     1.0     2.0         5             1165.0              500         none   
3     1.0     2.0         5              725.0              690          NaN   
4     1.0     1.0         4              940.0              500     Softball   
..    ...     ...       ...                ...              ...          ...   
120   1.0     1.0         5              940.0              500     Softball   
121   1.0     NaN         4              940.0              500  basketball    
122   1.0     2.0         5              580.0              690         none   
123   2.0     2.0         1              940.0              500          NaN   
124   1.0     2.0         2              725.0              345          NaN   

     veggies_day  vitamins  waffle_calories                    weight  
0              5         1             1315                       187  
1              4         2              900                       155  
2              5         1              900  I'm not answering this.   
3              3         1             1315             Not sure, 240  
4              4         2              760                       190  
..           ...       ...              ...                       ...  
120            5         1             1315                       156  
121            5         2             1315                       180  
122            4         2             1315                       120  
123            3 

In [92]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'cook', 'comfort_food_reasons_coded.1', 'cuisine', 'diet_current',
       'diet_current_coded', 'drink', 'eating_changes', 'eating_changes_coded',
       'eating_changes_coded1', 'eating_out', 'employment', 'ethnic_food',
       'exercise', 'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories

#### cook

In [93]:
df['cook']

0      2.0
1      3.0
2      1.0
3      2.0
4      1.0
      ... 
120    3.0
121    3.0
122    3.0
123    3.0
124    NaN
Name: cook, Length: 125, dtype: float64

In [95]:
df['cook'].isnull().sum()

3

In [96]:
df['cook'].unique()

array([ 2.,  3.,  1.,  5.,  4., nan])

In [99]:
df['cook'] = df['cook'].fillna(0).astype(int)

In [100]:
df['cook'].unique()

array([2, 3, 1, 5, 4, 0])

In [101]:
df['cook'] = df['cook'].replace({
    1 : "Everyday",
    2 : "A couple of times a week",
    3 : "Whenever I can, but that is not very often",
    4 : "I only help a little during holidays",
    5 : "Never, I  really do not  know my way around a kitchen"
})

In [102]:
df['cook'].unique()

array(['A couple of times a week',
       'Whenever I can, but that is not very often', 'Everyday',
       'Never, I  really do not  know my way around a kitchen',
       'I only help a little during holidays', 0], dtype=object)

#### cuisine

In [103]:
df['cuisine']

0      NaN
1      1.0
2      3.0
3      2.0
4      2.0
      ... 
120    1.0
121    NaN
122    NaN
123    1.0
124    3.0
Name: cuisine, Length: 125, dtype: float64

In [104]:
df['cuisine'].isnull().sum()

17

In [105]:
df['cuisine'].unique()

array([nan,  1.,  3.,  2.,  6.,  4.,  5.])

In [106]:
df['cuisine'] = df['cuisine'].fillna(0).astype(int)

In [111]:
df['cuisine'] = df['cuisine'].replace({
    1 : "American",
    2 : "Mexican / Spanish",
    3 : "Korean / Asian",
    4 : "Indian",
    5 : "American inspired internatioonal dishes",
    6 : "other"
})

In [112]:
df['cuisine']

0                     0
1              American
2        Korean / Asian
3      Mexican /Spanish
4      Mexican /Spanish
             ...       
120            American
121                   0
122                   0
123            American
124      Korean / Asian
Name: cuisine, Length: 125, dtype: object

#### diet current

In [114]:
df['diet_current']

0                                  eat good and exercise
1      I eat about three times a day with some snacks...
2      toast and fruit for breakfast, salad for lunch...
3      College diet, cheap and easy foods most nights...
4      I try to eat healthy but often struggle becaus...
                             ...                        
120    My diet consists mainly of coffee, water, frui...
121    A college student with an imbalanced diet tryi...
122                               Rice, oatmeal, and tea
123    I try to eat as healthy as possible everyday. ...
124            high in protein and low in carbohydrates.
Name: diet_current, Length: 125, dtype: object

In [115]:
df['diet_current'].unique()

array(['eat good and exercise',
       "I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ",
       'toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner',
       'College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals  ',
       'I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ',
       "My current diet is terrible. I barely have time to eat a meal in a day. When i do eat it's mostly not healthy.",
       'I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.',
       'I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.',
       'I eat whatever I want in moderation.',
       "I eat healthy all 

#### diet_current_coded

In [116]:
df['diet_current_coded'].isnull().sum()

0

In [117]:
df['diet_current_coded'].unique()

array([1, 2, 3, 4], dtype=int64)

In [127]:
df['diet_current_coded'] = df['diet_current_coded'].replace({
     1 : "Healthy / Balanced / Moderated",
     2 : "Unhealthy / Cheap / too much / Random",
     3 : "The same thing over and over",
     4 : "Unclear"
})

In [128]:
df['diet_current_coded'].unique()

array(['Healthy / Balanced / Moderated',
       'Unhealthy / Cheap / too much / Random',
       'The same thing over and over', 'Unclear'], dtype=object)

In [129]:
df['diet_current_coded']

0             Healthy / Balanced / Moderated
1      Unhealthy / Cheap / too much / Random
2               The same thing over and over
3      Unhealthy / Cheap / too much / Random
4      Unhealthy / Cheap / too much / Random
                       ...                  
120    Unhealthy / Cheap / too much / Random
121    Unhealthy / Cheap / too much / Random
122    Unhealthy / Cheap / too much / Random
123           Healthy / Balanced / Moderated
124           Healthy / Balanced / Moderated
Name: diet_current_coded, Length: 125, dtype: object

#### drink

In [131]:
df['drink']

0      1.0
1      2.0
2      1.0
3      2.0
4      2.0
      ... 
120    2.0
121    1.0
122    1.0
123    2.0
124    1.0
Name: drink, Length: 125, dtype: float64

In [132]:
df['drink'].isnull().sum()

2

In [133]:
df['drink'].unique()

array([ 1.,  2., nan])

In [134]:
df['drink'] = df['drink'].fillna(0).astype(int)

In [135]:
df['drink'] = df['drink']

0      1
1      2
2      1
3      2
4      2
      ..
120    2
121    1
122    1
123    2
124    1
Name: drink, Length: 125, dtype: int32

In [136]:
df['drink'] = df['drink'].replace({1  : "Orange Juice", 2 : "Soda"})

In [137]:
df['drink']

0      Orange Juice
1              Soda
2      Orange Juice
3              Soda
4              Soda
           ...     
120            Soda
121    Orange Juice
122    Orange Juice
123            Soda
124    Orange Juice
Name: drink, Length: 125, dtype: object

#### eating changes

In [138]:
df['eating_changes']

0                                            eat faster 
1                            I eat out more than usual. 
2      sometimes choosing to eat fast food instead of...
3         Accepting cheap and premade/store bought foods
4      I have eaten generally the same foods but I do...
                             ...                        
120    I have noticed there is less time for a prepar...
121    Eating Pizza as an excuse when there is nothin...
122                                            less rice
123    I don't eat as much on a daily basis since com...
124              I have learned to eat more vegetables. 
Name: eating_changes, Length: 125, dtype: object

#### eating changes coded

In [139]:
df['eating_changes_coded'].isnull().sum()

0

In [140]:
df['eating_changes_coded'].unique()

array([1, 3, 2, 4], dtype=int64)

In [141]:
df['eating_changes_coded'] = df['eating_changes_coded'].replace({
    1 : "Worse",
    2 : "Better",
    3 : "The same",
    4 : "unclear"
})

In [142]:
df['eating_changes_coded'].unique()

array(['Worse', 'The same', 'Better', 'unclear'], dtype=object)