In [1]:
import pandas as pd
import numpy as np
import re


In [2]:
df = pd.read_csv(r'C:/Users/OMKAR/Desktop/Practice/Food_Data_Processing/Data/food_coded_uncleaned.csv')

In [3]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

In [4]:
df.tail()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
120    3.5       1          1               610           4.0           420.0   
121      3       1          1               265           2.0           315.0   
122  3.882       1          1               720           NaN           420.0   
123      3       2          1               720           4.0           420.0   
124    3.9       1          1               430           NaN           315.0   

     coffee                             comfort_food  \
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3         1   
124             725.0              345          NaN           4         2   

     waffle_calories  weight  
120             1315     156  
121             1315     180  
122             1315     120  
123             1315     135  
124              575     135  

[5 rows x 61 columns]

In [5]:
df.shape

(125, 61)

In [6]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         21
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [8]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       

#### GPA

In [9]:
df['GPA']

0        2.4
1      3.654
2        3.3
3        3.2
4        3.5
       ...  
120      3.5
121        3
122    3.882
123        3
124      3.9
Name: GPA, Length: 125, dtype: object

In [10]:
df['GPA'].isnull().sum()

2

In [11]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '3.79 bitch', '2.71', '3.68',
       '3.75', '3.92', 'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [17]:
df['GPA'] = df['GPA'].replace('[a-z[A-Z]', '', regex = True)
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', ' ',
       '2.6', '3.67', '3.73', '3.79 ', '2.71', '3.68', '3.75', '3.92', '',
       '3.77', '3.63', '3.882'], dtype=object)

In [24]:
df['GPA'] = df['GPA'].replace(' ', np.nan)
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', '2.6',
       '3.67', '3.73', '3.79 ', '2.71', '3.68', '3.75', '3.92', '3.77',
       '3.63', '3.882'], dtype=object)

In [26]:
df['GPA'] = df['GPA'].apply(lambda x: '{:.1f}'.format(round(float(x), 1)))
df['GPA']

0      2.4
1      3.7
2      3.3
3      3.2
4      3.5
      ... 
120    3.5
121    3.0
122    3.9
123    3.0
124    3.9
Name: GPA, Length: 125, dtype: object

In [27]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0  2.4       2          1               430           NaN           315.0   
1  3.7       1          1               610           3.0           420.0   
2  3.3       1          1               720           4.0           420.0   
3  3.2       1          1               430           3.0           420.0   
4  3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

#### Gender

In [28]:
df['Gender'].isnull().sum()

0

In [29]:
df['Gender'].unique()

array([2, 1], dtype=int64)

In [30]:
df['Gender'] = df['Gender'].replace({1 :  'Female', 2 : 'Male'})

In [31]:
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0  2.4    Male          1               430           NaN           315.0   
1  3.7  Female          1               610           3.0           420.0   
2  3.3  Female          1               720           4.0           420.0   
3  3.2  Female          1               430           3.0           420.0   
4  3.5  Female          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

####  Breakfast

In [33]:
df['breakfast'].isnull().sum()

0

In [34]:
df['breakfast'].unique()

array([1, 2], dtype=int64)

In [35]:
df['breakfast'] = df['breakfast'].replace({1 : 'Cereal', 2 : 'Donut'})
df['breakfast']

0      Cereal
1      Cereal
2      Cereal
3      Cereal
4      Cereal
        ...  
120    Cereal
121    Cereal
122    Cereal
123    Cereal
124    Cereal
Name: breakfast, Length: 125, dtype: object

In [36]:
df['breakfast'].unique()

array(['Cereal', 'Donut'], dtype=object)

In [37]:
df.head()

GPA  Gender breakfast  calories_chicken  calories_day  calories_scone  \
0  2.4    Male    Cereal               430           NaN           315.0   
1  3.7  Female    Cereal               610           3.0           420.0   
2  3.3  Female    Cereal               720           4.0           420.0   
3  3.2  Female    Cereal               430           3.0           420.0   
4  3.5  Female    Cereal               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

#### Calories_chicken


In [39]:
df['calories_chicken'].isnull().sum()

0

In [40]:
df['calories_chicken'].unique()

array([430, 610, 720, 265], dtype=int64)

In [42]:
df['calories_chicken'] = df['calories_chicken'].replace({265 : 1, 430 : 2, 610 : 3, 720 : 4})
df['calories_chicken']

0      2
1      3
2      4
3      2
4      4
      ..
120    3
121    1
122    4
123    4
124    2
Name: calories_chicken, Length: 125, dtype: int64

In [43]:
df

GPA  Gender breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4    Male    Cereal                 2           NaN           315.0   
1    3.7  Female    Cereal                 3           3.0           420.0   
2    3.3  Female    Cereal                 4           4.0           420.0   
3    3.2  Female    Cereal                 2           3.0           420.0   
4    3.5  Female    Cereal                 4           2.0           420.0   
..   ...     ...       ...               ...           ...             ...   
120  3.5  Female    Cereal                 3           4.0           420.0   
121  3.0  Female    Cereal                 1           2.0           315.0   
122  3.9  Female    Cereal                 4           NaN           420.0   
123  3.0    Male    Cereal                 4           4.0           420.0   
124  3.9  Female    Cereal                 2           NaN           315.0   

     coffee                             comfort_food  \
0         1                                     none   
1         2              chocolate, chips, ice cream   
2         2          frozen yogurt, pizza, fast food   
3         2         Pizza, Mac and cheese, ice cream   
4         2             Ice cream, chocolate, chips    
..      ...                                      ...   
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1   
1                           1.0  ...   1.0     1.0          2   
2                           1.0  ...   1.0     2.0          5   
3                           2.0  ...   1.0     2.0          5   
4                           1.0  ...   1.0     1.0          4   
..                          ...  ...   ...     ...        ...   
120                         NaN  ...   1.0     1.0          5   
121                         NaN  ...   1.0     NaN          4   
122                         NaN  ...   1.0     2.0          5   
123                         NaN  ...   2.0     2.0          1   
124                         NaN  ...   1.0     2.0          2   

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1   
1               725.0              690  Basketball            4         2   
2              1165.0              500         none           5         1   
3               725.0              690          NaN           3         1   
4               940.0              500     Softball           4         2   
..                ...              ...          ...         ...       ...   
120             940.0              500     Softball           5         1   
121             940.0              500  basketball            5         2   
122             580.0              690         none           4         2   
123             940.0              500          NaN           3         1   
124             725.0              345          NaN           4         2   

     waffle_calories                    

#### calories day

In [44]:
df['calories_day'].isnull().sum()

19

In [45]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [46]:
df['calories_day'] = df['calories_day'].astype(str).str.replace('\.0$', '')

C:\Users\OMKAR\AppData\Local\Temp/ipykernel_11664/1536826737.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['calories_day'] = df['calories_day'].astype(str).str.replace('\.0$', '')


In [47]:
df['calories_day'].unique()

array(['nan', '3', '4', '2'], dtype=object)

In [50]:
df['calories_day'] = df['calories_day'].replace({
    '1' : "Don't know how many calorie should consume",
    '2' : "Not at all important",
    '3' : "Moderatelly important",
    '4' : "Very Important"
})

In [49]:
df['calories_day']

0      nan
1        3
2        4
3        3
4        2
      ... 
120      4
121      2
122    nan
123      4
124    nan
Name: calories_day, Length: 125, dtype: object